/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
    const { nodes, materials } = useGLTF('/HTML.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[-29.971, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[50, 26.489, 50]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Curve007.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Curve007_1.geometry}
                    material={materials['Material.007']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Curve007_2.geometry}
                    material={materials['Material.015']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Curve007_3.geometry}
                    material={materials['Material.016']}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/HTML.glb')


